version: "3.7"
services:
  mysql-service:
    image: mysql:latest
    volumes:
      - ./docker_tmp/mysql:/var/lib/mysql
    ports:
      - "33070:33060"
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "cognitive_exercises_dev_admin"
      MYSQL_PASSWORD: "admin"
  cognitive-exercises-main:
    build: ./
    image: cognitive-exercises-main:0.0.2-SNAPSHOT
    ports:
      - "8081:8081"
    depends_on:
      - mysql-service
#      - rabbit-service
#      - cognitive-exercises-gateway
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/cognitive_exercises_dev?serverTimezone=UTC
#      SPRING_RABBITMQ_HOST: rabbit-service
#      SPRING_RABBITMQ_PORT: 5672
#      KEYCLOAK_AUTH-SERVER-URL: http://keycloak-service:8080/auth
#      FRONTEND-ADDRESS: http://localhost:80/api
#       seems that sth is wrong with setting this value here, for now it is hardcoded in application.properties
#      CUTOM-KEYCLOAK-PARAMS_ADMIN-CLI_SECRET: WxIieRB64oxJvFmsm7IVZJy2JMd2KHoG
