server:
  port: 8081
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/rife
    username: cognitive_exercises_dev
    password: admin
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: update
              create-target: database_create.sql

logging:
  level:
    com.zelazobeton.cognitiveexercises: DEBUG
    org.springframework.transaction: DEBUG