-- CREATE DATABASE cognitive_exercises_dev;
--
-- CREATE USER 'cognitive_exercises_dev_user'@'localhost' IDENTIFIED BY 'user';
-- CREATE USER 'cognitive_exercises_dev_admin'@'localhost' IDENTIFIED BY 'admin';
--
-- GRANT SELECT ON cognitive_exercises_dev.* to 'cognitive_exercises_dev_user'@'localhost';
-- GRANT INSERT ON cognitive_exercises_dev.* to 'cognitive_exercises_dev_user'@'localhost';
-- GRANT DELETE ON cognitive_exercises_dev.* to 'cognitive_exercises_dev_user'@'localhost';
-- GRANT UPDATE ON cognitive_exercises_dev.* to 'cognitive_exercises_dev_user'@'localhost';

-- GRANT SELECT ON cognitive_exercises_dev.* to 'cognitive_exercises_dev_admin'@'localhost';
-- GRANT INSERT ON cognitive_exercises_dev.* to 'cognitive_exercises_dev_admin'@'localhost';
-- GRANT DELETE ON cognitive_exercises_dev.* to 'cognitive_exercises_dev_admin'@'localhost';
-- GRANT UPDATE ON cognitive_exercises_dev.* to 'cognitive_exercises_dev_admin'@'localhost';
-- GRANT CREATE ON cognitive_exercises_dev.* to 'cognitive_exercises_dev_admin'@'localhost';
-- GRANT ALTER ON cognitive_exercises_dev.* to 'cognitive_exercises_dev_admin'@'localhost';
-- GRANT EXECUTE ON cognitive_exercises_dev.* to 'cognitive_exercises_dev_admin'@'localhost';
-- GRANT CREATE VIEW ON cognitive_exercises_dev.* to 'cognitive_exercises_dev_admin'@'localhost';
-- GRANT DROP ON cognitive_exercises_dev.* to 'cognitive_exercises_dev_admin'@'localhost';